// Package api_docs Code generated by swaggo/swag. DO NOT EDIT
package api_docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/executions/{execution_uuid}/logs": {
            "post": {
                "description": "Append a log entry to an execution by execution UUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "Append log to execution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution UUID",
                        "name": "execution_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Log entry",
                        "name": "log",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/executions/{execution_uuid}/status": {
            "patch": {
                "description": "Update the status of an execution (SUCCESS, FAILED, RUNNING)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "Update execution status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution UUID",
                        "name": "execution_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status update",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "description": "Retrieve a list of all projects",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get all projects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Project"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new project with auto-generated UUID and API key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Create a new project",
                "parameters": [
                    {
                        "description": "Project creation request",
                        "name": "project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Project"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}": {
            "put": {
                "description": "Update an existing project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Update a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Project update request",
                        "name": "project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Project"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/task-groups": {
            "get": {
                "description": "Retrieve all task groups belonging to a project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task-groups"
                ],
                "summary": "Get task groups by project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TaskGroup"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new task group in a project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task-groups"
                ],
                "summary": "Create a new task group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task group creation request",
                        "name": "task_group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateTaskGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.TaskGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/task-groups/{group_uuid}": {
            "get": {
                "description": "Retrieve a task group by its UUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task-groups"
                ],
                "summary": "Get a task group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task Group UUID",
                        "name": "group_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TaskGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing task group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task-groups"
                ],
                "summary": "Update a task group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task Group UUID",
                        "name": "group_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task group update request",
                        "name": "task_group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateTaskGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TaskGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing task group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task-groups"
                ],
                "summary": "Delete a task group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task Group UUID",
                        "name": "group_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/task-groups/{group_uuid}/start": {
            "post": {
                "description": "Manually start all tasks in a task group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task-groups"
                ],
                "summary": "Start a task group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task Group UUID",
                        "name": "group_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/task-groups/{group_uuid}/stop": {
            "post": {
                "description": "Manually stop all tasks in a task group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task-groups"
                ],
                "summary": "Stop a task group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task Group UUID",
                        "name": "group_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/task-groups/{group_uuid}/tasks": {
            "get": {
                "description": "Retrieve all tasks belonging to a task group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "task-groups"
                ],
                "summary": "Get tasks in a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task Group UUID",
                        "name": "group_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Task"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/tasks": {
            "get": {
                "description": "Retrieve all tasks belonging to a project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Get tasks by project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Task"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new scheduled task in a project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Create a new task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task creation request",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/tasks/{task_uuid}": {
            "put": {
                "description": "Update an existing scheduled task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Update a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task UUID",
                        "name": "task_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task update request",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing scheduled task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Delete a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task UUID",
                        "name": "task_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/tasks/{task_uuid}/executions": {
            "get": {
                "description": "Retrieve all executions for a specific task filtered by date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "Get executions for a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task UUID",
                        "name": "task_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by date (YYYY-MM-DD format). Returns executions for that date only",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Execution"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/tasks/{task_uuid}/status": {
            "patch": {
                "description": "Update a task's status (ACTIVE or DISABLED) and update scheduler accordingly",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Update task status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task UUID",
                        "name": "task_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateProjectRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "execution_endpoint": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "models.CreateTaskGroupRequest": {
            "type": "object",
            "required": [
                "name",
                "project_id"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "end_time": {
                    "description": "Format: \"HH:MM\"",
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "project_id": {
                    "type": "string"
                },
                "start_time": {
                    "description": "Format: \"HH:MM\"",
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "ACTIVE",
                        "DISABLED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskGroupStatus"
                        }
                    ]
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "models.CreateTaskRequest": {
            "type": "object",
            "required": [
                "name",
                "project_id",
                "schedule_config",
                "schedule_type"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "project_id": {
                    "type": "string"
                },
                "schedule_config": {
                    "$ref": "#/definitions/models.ScheduleConfig"
                },
                "schedule_type": {
                    "enum": [
                        "RECURRING",
                        "ONEOFF"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ScheduleType"
                        }
                    ]
                },
                "status": {
                    "enum": [
                        "ACTIVE",
                        "RUNNING",
                        "DISABLED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskStatus"
                        }
                    ]
                },
                "task_group_id": {
                    "description": "Optional task group ID",
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "project_id is required"
                    ]
                },
                "error": {
                    "type": "string",
                    "example": "Invalid request"
                }
            }
        },
        "models.Execution": {
            "description": "Execution represents a task execution record",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "ended_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:05Z"
                },
                "error": {
                    "type": "string",
                    "example": "Connection timeout"
                },
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LogEntry"
                    }
                },
                "started_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "status": {
                    "enum": [
                        "PENDING",
                        "RUNNING",
                        "SUCCESS",
                        "FAILED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ExecutionStatus"
                        }
                    ],
                    "example": "PENDING"
                },
                "task_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "task_uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "models.ExecutionStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "FAILED"
            ],
            "x-enum-varnames": [
                "ExecutionStatusPending",
                "ExecutionStatusRunning",
                "ExecutionStatusSuccess",
                "ExecutionStatusFailed"
            ]
        },
        "models.Frequency": {
            "type": "object",
            "required": [
                "unit",
                "value"
            ],
            "properties": {
                "unit": {
                    "description": "Unit: \"s\" (seconds), \"m\" (minutes), \"h\" (hours)",
                    "enum": [
                        "s",
                        "m",
                        "h"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.FrequencyUnit"
                        }
                    ]
                },
                "value": {
                    "description": "Numeric value (e.g., 15)",
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "models.FrequencyUnit": {
            "type": "string",
            "enum": [
                "s",
                "m",
                "h"
            ],
            "x-enum-varnames": [
                "FrequencyUnitSecond",
                "FrequencyUnitMinute",
                "FrequencyUnitHour"
            ]
        },
        "models.HTTPTriggerConfig": {
            "type": "object",
            "required": [
                "method",
                "url"
            ],
            "properties": {
                "body": {},
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "type": "string"
                },
                "timeout": {
                    "type": "integer",
                    "maximum": 300,
                    "minimum": 1
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.LogEntry": {
            "type": "object",
            "properties": {
                "level": {
                    "description": "info, warn, error",
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.Project": {
            "description": "Project represents a project entity that contains tasks",
            "type": "object",
            "properties": {
                "alert_emails": {
                    "type": "string",
                    "example": "admin@example.com,ops@example.com"
                },
                "api_key": {
                    "type": "string",
                    "example": "sk_live_abc123..."
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Project description"
                },
                "execution_endpoint": {
                    "type": "string",
                    "example": "https://api.example.com/execute"
                },
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "name": {
                    "type": "string",
                    "example": "My Project"
                },
                "project_users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProjectUser"
                    }
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "models.ProjectUser": {
            "description": "ProjectUser represents a user associated with a project",
            "type": "object",
            "required": [
                "email",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "role": {
                    "enum": [
                        "admin",
                        "readonly"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ProjectUserRole"
                        }
                    ],
                    "example": "admin"
                }
            }
        },
        "models.ProjectUserRole": {
            "type": "string",
            "enum": [
                "admin",
                "readonly"
            ],
            "x-enum-varnames": [
                "ProjectUserRoleAdmin",
                "ProjectUserRoleReadonly"
            ]
        },
        "models.ScheduleConfig": {
            "type": "object",
            "required": [
                "timezone"
            ],
            "properties": {
                "cron_expression": {
                    "description": "If provided, TimeRange and DaysOfWeek are ignored",
                    "type": "string"
                },
                "days_of_week": {
                    "description": "Used only if CronExpression is not provided",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "exclusions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "time_range": {
                    "description": "Used only if CronExpression is not provided",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TimeRange"
                        }
                    ]
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "models.ScheduleType": {
            "type": "string",
            "enum": [
                "RECURRING",
                "ONEOFF"
            ],
            "x-enum-varnames": [
                "ScheduleTypeRecurring",
                "ScheduleTypeOneOff"
            ]
        },
        "models.Task": {
            "description": "Task represents a scheduled task entity",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Backup database daily"
                },
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string",
                    "example": "Daily Backup"
                },
                "project_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "schedule_config": {
                    "$ref": "#/definitions/models.ScheduleConfig"
                },
                "schedule_type": {
                    "enum": [
                        "RECURRING",
                        "ONEOFF"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ScheduleType"
                        }
                    ],
                    "example": "RECURRING"
                },
                "state": {
                    "description": "System-controlled: based on time window",
                    "enum": [
                        "RUNNING",
                        "NOT_RUNNING"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskState"
                        }
                    ],
                    "example": "NOT_RUNNING"
                },
                "status": {
                    "enum": [
                        "ACTIVE",
                        "RUNNING",
                        "DISABLED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskStatus"
                        }
                    ],
                    "example": "ACTIVE"
                },
                "task_group_id": {
                    "description": "Optional reference to task group",
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "trigger_config": {
                    "description": "Deprecated: Tasks now use project's execution_endpoint",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TriggerConfig"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "models.TaskGroup": {
            "description": "TaskGroup represents a group of tasks that can be controlled together",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Tasks that run in the morning"
                },
                "end_time": {
                    "description": "Format: \"HH:MM\"",
                    "type": "string",
                    "example": "17:00"
                },
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "name": {
                    "type": "string",
                    "example": "Morning Tasks"
                },
                "project_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "start_time": {
                    "description": "Format: \"HH:MM\"",
                    "type": "string",
                    "example": "09:00"
                },
                "state": {
                    "description": "System-controlled: based on time window",
                    "enum": [
                        "RUNNING",
                        "NOT_RUNNING"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskGroupState"
                        }
                    ],
                    "example": "NOT_RUNNING"
                },
                "status": {
                    "enum": [
                        "ACTIVE",
                        "DISABLED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskGroupStatus"
                        }
                    ],
                    "example": "ACTIVE"
                },
                "timezone": {
                    "description": "IANA timezone (e.g., \"America/New_York\")",
                    "type": "string",
                    "example": "America/New_York"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "models.TaskGroupState": {
            "type": "string",
            "enum": [
                "RUNNING",
                "NOT_RUNNING"
            ],
            "x-enum-varnames": [
                "TaskGroupStateRunning",
                "TaskGroupStateNotRunning"
            ]
        },
        "models.TaskGroupStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "DISABLED"
            ],
            "x-enum-varnames": [
                "TaskGroupStatusActive",
                "TaskGroupStatusDisabled"
            ]
        },
        "models.TaskState": {
            "type": "string",
            "enum": [
                "RUNNING",
                "NOT_RUNNING"
            ],
            "x-enum-varnames": [
                "TaskStateRunning",
                "TaskStateNotRunning"
            ]
        },
        "models.TaskStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "DISABLED"
            ],
            "x-enum-varnames": [
                "TaskStatusActive",
                "TaskStatusDisabled"
            ]
        },
        "models.TimeRange": {
            "type": "object",
            "required": [
                "end",
                "frequency",
                "start"
            ],
            "properties": {
                "end": {
                    "description": "Format: \"HH:MM\"",
                    "type": "string"
                },
                "frequency": {
                    "description": "Frequency with value and unit (e.g., {value: 15, unit: \"m\"})",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Frequency"
                        }
                    ]
                },
                "start": {
                    "description": "Format: \"HH:MM\"",
                    "type": "string"
                }
            }
        },
        "models.TriggerConfig": {
            "type": "object",
            "properties": {
                "http": {
                    "$ref": "#/definitions/models.HTTPTriggerConfig"
                },
                "type": {
                    "enum": [
                        "HTTP"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TriggerType"
                        }
                    ]
                }
            }
        },
        "models.TriggerType": {
            "type": "string",
            "enum": [
                "HTTP"
            ],
            "x-enum-varnames": [
                "TriggerTypeHTTP"
            ]
        },
        "models.UpdateProjectRequest": {
            "type": "object",
            "properties": {
                "alert_emails": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "execution_endpoint": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "project_users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProjectUser"
                    }
                }
            }
        },
        "models.UpdateTaskGroupRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "end_time": {
                    "description": "Format: \"HH:MM\"",
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "start_time": {
                    "description": "Format: \"HH:MM\"",
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "ACTIVE",
                        "DISABLED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskGroupStatus"
                        }
                    ]
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "models.UpdateTaskRequest": {
            "type": "object",
            "required": [
                "name",
                "schedule_config",
                "schedule_type"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "schedule_config": {
                    "$ref": "#/definitions/models.ScheduleConfig"
                },
                "schedule_type": {
                    "enum": [
                        "RECURRING",
                        "ONEOFF"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ScheduleType"
                        }
                    ]
                },
                "status": {
                    "enum": [
                        "ACTIVE",
                        "RUNNING",
                        "DISABLED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TaskStatus"
                        }
                    ]
                },
                "task_group_id": {
                    "description": "Optional task group ID",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Cron Observer API",
	Description:      "API for managing scheduled tasks and task groups",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
