version: "3"

vars:
  BACKEND_DIR: backend
  EXAMPLE_CLIENT_DIR: example-client-nestjs
  UI_DIR: UI

tasks:
  # Start MongoDB and run migrations, then start the backend server
  backend:
    desc: Start the backend server (MongoDB + migrations + server)
    dir: "{{.BACKEND_DIR}}"
    preconditions:
      - test -f go.mod
    cmds:
      - task: setup-db
      - echo "🚀 Starting backend server..."
      - go run cmd/server/main.go

  # Setup database (MongoDB + migrations)
  setup-db:
    desc: Start MongoDB and run migrations (no auth for local dev)
    cmds:
      - echo "📦 Starting MongoDB..."
      - docker-compose up -d mongodb
      - echo "⏳ Waiting for MongoDB to be ready..."
      - sleep 5
      - echo "🔄 Running migrations..."
      - task: migrate
      - echo "✅ Database setup complete!"

  # Run database migrations
  migrate:
    desc: Run database migrations
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go run cmd/migrate/main.go create-collections

  # Start the NestJS example client
  example-client-nestjs:
    desc: Start the NestJS example client
    dir: "{{.EXAMPLE_CLIENT_DIR}}"
    preconditions:
      - test -f package.json
    cmds:
      - echo "🚀 Starting NestJS example client..."
      - npm run start:dev

  # Start the UI
  ui:
    desc: Start the UI frontend
    dir: "{{.UI_DIR}}"
    preconditions:
      - test -f package.json
    cmds:
      - echo "🚀 Starting UI..."
      - pnpm dev

  # Generate OpenAPI documentation and API client
  gen:openapi:
    desc: Generate OpenAPI documentation (backend) and TypeScript API client (frontend)
    cmds:
      - ./scripts/generate-openapi.sh

  # Generate gomock mocks
  gen:mocks:
    desc: Generate gomock mocks for interfaces
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - echo "🔨 Generating mocks..."
      - go run go.uber.org/mock/mockgen@latest -source=internal/repositories/repository.go -destination=mocks/mock_repository.go -package=mocks
      - go run go.uber.org/mock/mockgen@latest -source=internal/deleteworker/worker.go -destination=mocks/mock_worker.go -package=mocks
      - echo "✅ Mocks generated successfully!"

  # Run tests
  test:
    desc: Run all backend tests
    dir: "{{.BACKEND_DIR}}"
    preconditions:
      - test -f go.mod
    cmds:
      - echo "Running tests..."
      - go test ./... -v
      - echo "Tests completed!"

  # Run tests for a specific package
  test:package:
    desc: "Run tests for a specific package (usage: task test:package -- package-path)"
    dir: "{{.BACKEND_DIR}}"
    preconditions:
      - test -f go.mod
    cmds:
      - echo "Running tests for {{.CLI_ARGS}}..."
      - go test {{.CLI_ARGS}} -v
      - echo "Tests completed!"

  # Run tests with coverage
  test:coverage:
    desc: Run all tests with coverage report
    dir: "{{.BACKEND_DIR}}"
    preconditions:
      - test -f go.mod
    cmds:
      - echo "Running tests with coverage..."
      - go test ./... -v -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  # Cleanup: Kill all services and free ports
  cleanup:
    desc: Clean up all services and free ports
    cmds:
      - ./scripts/cleanup.sh

  # Start all services (backend, example-client-nestjs, and UI)
  up:
    desc: Start all services (backend, example-client-nestjs, and UI)
    cmds:
      - task: cleanup
      - |
        echo "🚀 Starting all services..."
        PIDS=()
        task backend &
        PIDS+=($!)
        task example-client-nestjs &
        PIDS+=($!)
        task ui &
        PIDS+=($!)
        wait

  # Build and push Docker image
  build:
    desc: Build Docker image and optionally push to Docker Hub
    cmds:
      - bash scripts/build-and-push.sh {{.CLI_ARGS}}
