// Code generated by MockGen. DO NOT EDIT.
// Source: internal/deleteworker/worker.go
//
// Generated by this command:
//
//	mockgen -source=internal/deleteworker/worker.go -destination=mocks/mock_worker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	events "github.com/yourusername/cron-observer/backend/internal/events"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskUnregisterer is a mock of TaskUnregisterer interface.
type MockTaskUnregisterer struct {
	ctrl     *gomock.Controller
	recorder *MockTaskUnregistererMockRecorder
	isgomock struct{}
}

// MockTaskUnregistererMockRecorder is the mock recorder for MockTaskUnregisterer.
type MockTaskUnregistererMockRecorder struct {
	mock *MockTaskUnregisterer
}

// NewMockTaskUnregisterer creates a new mock instance.
func NewMockTaskUnregisterer(ctrl *gomock.Controller) *MockTaskUnregisterer {
	mock := &MockTaskUnregisterer{ctrl: ctrl}
	mock.recorder = &MockTaskUnregistererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskUnregisterer) EXPECT() *MockTaskUnregistererMockRecorder {
	return m.recorder
}

// UnregisterTask mocks base method.
func (m *MockTaskUnregisterer) UnregisterTask(taskUUID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnregisterTask", taskUUID)
}

// UnregisterTask indicates an expected call of UnregisterTask.
func (mr *MockTaskUnregistererMockRecorder) UnregisterTask(taskUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterTask", reflect.TypeOf((*MockTaskUnregisterer)(nil).UnregisterTask), taskUUID)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventPublisher) Publish(event events.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", event)
}

// Publish indicates an expected call of Publish.
func (mr *MockEventPublisherMockRecorder) Publish(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventPublisher)(nil).Publish), event)
}
