// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yourusername/cron-observer/backend/internal/deletequeue

package mocks

import (
	"context"
	"reflect"

	"github.com/yourusername/cron-observer/backend/internal/deletequeue"
	"go.uber.org/mock/gomock"
)

// MockDeleteJobPublisher is a mock of DeleteJobPublisher interface.
type MockDeleteJobPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteJobPublisherMockRecorder
}

// MockDeleteJobPublisherMockRecorder is the mock recorder for MockDeleteJobPublisher.
type MockDeleteJobPublisherMockRecorder struct {
	mock *MockDeleteJobPublisher
}

// NewMockDeleteJobPublisher creates a new mock instance.
func NewMockDeleteJobPublisher(ctrl *gomock.Controller) *MockDeleteJobPublisher {
	mock := &MockDeleteJobPublisher{ctrl: ctrl}
	mock.recorder = &MockDeleteJobPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteJobPublisher) EXPECT() *MockDeleteJobPublisherMockRecorder {
	return m.recorder
}

// PublishDeleteTask mocks base method.
func (m *MockDeleteJobPublisher) PublishDeleteTask(ctx context.Context, msg deletequeue.DeleteTaskMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDeleteTask", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDeleteTask indicates an expected call of PublishDeleteTask.
func (mr *MockDeleteJobPublisherMockRecorder) PublishDeleteTask(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeleteTask", reflect.TypeOf((*MockDeleteJobPublisher)(nil).PublishDeleteTask), ctx, msg)
}
