// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repositories/repository.go -destination=mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/yourusername/cron-observer/backend/internal/models"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AppendLogToExecution mocks base method.
func (m *MockRepository) AppendLogToExecution(ctx context.Context, executionUUID string, logEntry models.LogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendLogToExecution", ctx, executionUUID, logEntry)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendLogToExecution indicates an expected call of AppendLogToExecution.
func (mr *MockRepositoryMockRecorder) AppendLogToExecution(ctx, executionUUID, logEntry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendLogToExecution", reflect.TypeOf((*MockRepository)(nil).AppendLogToExecution), ctx, executionUUID, logEntry)
}

// CalculateTaskFailureStats mocks base method.
func (m *MockRepository) CalculateTaskFailureStats(ctx context.Context, projectID primitive.ObjectID, date string) (*models.StoredTaskFailureStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateTaskFailureStats", ctx, projectID, date)
	ret0, _ := ret[0].(*models.StoredTaskFailureStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateTaskFailureStats indicates an expected call of CalculateTaskFailureStats.
func (mr *MockRepositoryMockRecorder) CalculateTaskFailureStats(ctx, projectID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateTaskFailureStats", reflect.TypeOf((*MockRepository)(nil).CalculateTaskFailureStats), ctx, projectID, date)
}

// CreateExecution mocks base method.
func (m *MockRepository) CreateExecution(ctx context.Context, execution *models.Execution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExecution", ctx, execution)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExecution indicates an expected call of CreateExecution.
func (mr *MockRepositoryMockRecorder) CreateExecution(ctx, execution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExecution", reflect.TypeOf((*MockRepository)(nil).CreateExecution), ctx, execution)
}

// CreateProject mocks base method.
func (m *MockRepository) CreateProject(ctx context.Context, project *models.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockRepositoryMockRecorder) CreateProject(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockRepository)(nil).CreateProject), ctx, project)
}

// CreateTask mocks base method.
func (m *MockRepository) CreateTask(ctx context.Context, projectID string, task *models.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, projectID, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockRepositoryMockRecorder) CreateTask(ctx, projectID, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockRepository)(nil).CreateTask), ctx, projectID, task)
}

// CreateTaskGroup mocks base method.
func (m *MockRepository) CreateTaskGroup(ctx context.Context, projectID string, taskGroup *models.TaskGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskGroup", ctx, projectID, taskGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTaskGroup indicates an expected call of CreateTaskGroup.
func (mr *MockRepositoryMockRecorder) CreateTaskGroup(ctx, projectID, taskGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskGroup", reflect.TypeOf((*MockRepository)(nil).CreateTaskGroup), ctx, projectID, taskGroup)
}

// DeleteTask mocks base method.
func (m *MockRepository) DeleteTask(ctx context.Context, taskUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, taskUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockRepositoryMockRecorder) DeleteTask(ctx, taskUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockRepository)(nil).DeleteTask), ctx, taskUUID)
}

// DeleteTaskGroup mocks base method.
func (m *MockRepository) DeleteTaskGroup(ctx context.Context, taskGroupUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaskGroup", ctx, taskGroupUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaskGroup indicates an expected call of DeleteTaskGroup.
func (mr *MockRepositoryMockRecorder) DeleteTaskGroup(ctx, taskGroupUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaskGroup", reflect.TypeOf((*MockRepository)(nil).DeleteTaskGroup), ctx, taskGroupUUID)
}

// GetActiveTaskGroupsWithWindows mocks base method.
func (m *MockRepository) GetActiveTaskGroupsWithWindows(ctx context.Context) ([]*models.TaskGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveTaskGroupsWithWindows", ctx)
	ret0, _ := ret[0].([]*models.TaskGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveTaskGroupsWithWindows indicates an expected call of GetActiveTaskGroupsWithWindows.
func (mr *MockRepositoryMockRecorder) GetActiveTaskGroupsWithWindows(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveTaskGroupsWithWindows", reflect.TypeOf((*MockRepository)(nil).GetActiveTaskGroupsWithWindows), ctx)
}

// GetAllActiveTasks mocks base method.
func (m *MockRepository) GetAllActiveTasks(ctx context.Context) ([]*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActiveTasks", ctx)
	ret0, _ := ret[0].([]*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActiveTasks indicates an expected call of GetAllActiveTasks.
func (mr *MockRepositoryMockRecorder) GetAllActiveTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActiveTasks", reflect.TypeOf((*MockRepository)(nil).GetAllActiveTasks), ctx)
}

// GetAllProjects mocks base method.
func (m *MockRepository) GetAllProjects(ctx context.Context) ([]*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProjects", ctx)
	ret0, _ := ret[0].([]*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProjects indicates an expected call of GetAllProjects.
func (mr *MockRepositoryMockRecorder) GetAllProjects(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProjects", reflect.TypeOf((*MockRepository)(nil).GetAllProjects), ctx)
}

// GetExecutionByUUID mocks base method.
func (m *MockRepository) GetExecutionByUUID(ctx context.Context, executionUUID string) (*models.Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionByUUID", ctx, executionUUID)
	ret0, _ := ret[0].(*models.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutionByUUID indicates an expected call of GetExecutionByUUID.
func (mr *MockRepositoryMockRecorder) GetExecutionByUUID(ctx, executionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionByUUID", reflect.TypeOf((*MockRepository)(nil).GetExecutionByUUID), ctx, executionUUID)
}

// GetExecutionStatsByProject mocks base method.
func (m *MockRepository) GetExecutionStatsByProject(ctx context.Context, projectID primitive.ObjectID, days int) ([]*models.ExecutionStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionStatsByProject", ctx, projectID, days)
	ret0, _ := ret[0].([]*models.ExecutionStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutionStatsByProject indicates an expected call of GetExecutionStatsByProject.
func (mr *MockRepositoryMockRecorder) GetExecutionStatsByProject(ctx, projectID, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionStatsByProject", reflect.TypeOf((*MockRepository)(nil).GetExecutionStatsByProject), ctx, projectID, days)
}

// GetExecutionsByTaskUUID mocks base method.
func (m *MockRepository) GetExecutionsByTaskUUID(ctx context.Context, taskUUID string, startDate, endDate *time.Time) ([]*models.Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionsByTaskUUID", ctx, taskUUID, startDate, endDate)
	ret0, _ := ret[0].([]*models.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutionsByTaskUUID indicates an expected call of GetExecutionsByTaskUUID.
func (mr *MockRepositoryMockRecorder) GetExecutionsByTaskUUID(ctx, taskUUID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionsByTaskUUID", reflect.TypeOf((*MockRepository)(nil).GetExecutionsByTaskUUID), ctx, taskUUID, startDate, endDate)
}

// GetExecutionsByTaskUUIDPaginated mocks base method.
func (m *MockRepository) GetExecutionsByTaskUUIDPaginated(ctx context.Context, taskUUID string, startDate, endDate *time.Time, page, pageSize int) ([]*models.Execution, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionsByTaskUUIDPaginated", ctx, taskUUID, startDate, endDate, page, pageSize)
	ret0, _ := ret[0].([]*models.Execution)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetExecutionsByTaskUUIDPaginated indicates an expected call of GetExecutionsByTaskUUIDPaginated.
func (mr *MockRepositoryMockRecorder) GetExecutionsByTaskUUIDPaginated(ctx, taskUUID, startDate, endDate, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionsByTaskUUIDPaginated", reflect.TypeOf((*MockRepository)(nil).GetExecutionsByTaskUUIDPaginated), ctx, taskUUID, startDate, endDate, page, pageSize)
}

// GetFailureStatsByProject mocks base method.
func (m *MockRepository) GetFailureStatsByProject(ctx context.Context, projectID primitive.ObjectID, days int) ([]*models.FailedExecutionStats, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailureStatsByProject", ctx, projectID, days)
	ret0, _ := ret[0].([]*models.FailedExecutionStats)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFailureStatsByProject indicates an expected call of GetFailureStatsByProject.
func (mr *MockRepositoryMockRecorder) GetFailureStatsByProject(ctx, projectID, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailureStatsByProject", reflect.TypeOf((*MockRepository)(nil).GetFailureStatsByProject), ctx, projectID, days)
}

// GetProjectByID mocks base method.
func (m *MockRepository) GetProjectByID(ctx context.Context, projectID primitive.ObjectID) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, projectID)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockRepositoryMockRecorder) GetProjectByID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockRepository)(nil).GetProjectByID), ctx, projectID)
}

// GetProjectByName mocks base method.
func (m *MockRepository) GetProjectByName(ctx context.Context, name string) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByName", ctx, name)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByName indicates an expected call of GetProjectByName.
func (mr *MockRepositoryMockRecorder) GetProjectByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByName", reflect.TypeOf((*MockRepository)(nil).GetProjectByName), ctx, name)
}

// GetStoredTaskFailureStats mocks base method.
func (m *MockRepository) GetStoredTaskFailureStats(ctx context.Context, projectID primitive.ObjectID, date string) (*models.StoredTaskFailureStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoredTaskFailureStats", ctx, projectID, date)
	ret0, _ := ret[0].(*models.StoredTaskFailureStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoredTaskFailureStats indicates an expected call of GetStoredTaskFailureStats.
func (mr *MockRepositoryMockRecorder) GetStoredTaskFailureStats(ctx, projectID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoredTaskFailureStats", reflect.TypeOf((*MockRepository)(nil).GetStoredTaskFailureStats), ctx, projectID, date)
}

// GetTaskByUUID mocks base method.
func (m *MockRepository) GetTaskByUUID(ctx context.Context, taskUUID string) (*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByUUID", ctx, taskUUID)
	ret0, _ := ret[0].(*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByUUID indicates an expected call of GetTaskByUUID.
func (mr *MockRepositoryMockRecorder) GetTaskByUUID(ctx, taskUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByUUID", reflect.TypeOf((*MockRepository)(nil).GetTaskByUUID), ctx, taskUUID)
}

// GetTaskFailuresByDate mocks base method.
func (m *MockRepository) GetTaskFailuresByDate(ctx context.Context, projectID primitive.ObjectID, date string) ([]*models.TaskFailureStats, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskFailuresByDate", ctx, projectID, date)
	ret0, _ := ret[0].([]*models.TaskFailureStats)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTaskFailuresByDate indicates an expected call of GetTaskFailuresByDate.
func (mr *MockRepositoryMockRecorder) GetTaskFailuresByDate(ctx, projectID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskFailuresByDate", reflect.TypeOf((*MockRepository)(nil).GetTaskFailuresByDate), ctx, projectID, date)
}

// GetTaskGroupByID mocks base method.
func (m *MockRepository) GetTaskGroupByID(ctx context.Context, taskGroupID primitive.ObjectID) (*models.TaskGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskGroupByID", ctx, taskGroupID)
	ret0, _ := ret[0].(*models.TaskGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskGroupByID indicates an expected call of GetTaskGroupByID.
func (mr *MockRepositoryMockRecorder) GetTaskGroupByID(ctx, taskGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskGroupByID", reflect.TypeOf((*MockRepository)(nil).GetTaskGroupByID), ctx, taskGroupID)
}

// GetTaskGroupByUUID mocks base method.
func (m *MockRepository) GetTaskGroupByUUID(ctx context.Context, taskGroupUUID string) (*models.TaskGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskGroupByUUID", ctx, taskGroupUUID)
	ret0, _ := ret[0].(*models.TaskGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskGroupByUUID indicates an expected call of GetTaskGroupByUUID.
func (mr *MockRepositoryMockRecorder) GetTaskGroupByUUID(ctx, taskGroupUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskGroupByUUID", reflect.TypeOf((*MockRepository)(nil).GetTaskGroupByUUID), ctx, taskGroupUUID)
}

// GetTaskGroupsByProjectID mocks base method.
func (m *MockRepository) GetTaskGroupsByProjectID(ctx context.Context, projectID primitive.ObjectID) ([]*models.TaskGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskGroupsByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]*models.TaskGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskGroupsByProjectID indicates an expected call of GetTaskGroupsByProjectID.
func (mr *MockRepositoryMockRecorder) GetTaskGroupsByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskGroupsByProjectID", reflect.TypeOf((*MockRepository)(nil).GetTaskGroupsByProjectID), ctx, projectID)
}

// GetTasksByGroupID mocks base method.
func (m *MockRepository) GetTasksByGroupID(ctx context.Context, taskGroupID primitive.ObjectID) ([]*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByGroupID", ctx, taskGroupID)
	ret0, _ := ret[0].([]*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByGroupID indicates an expected call of GetTasksByGroupID.
func (mr *MockRepositoryMockRecorder) GetTasksByGroupID(ctx, taskGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByGroupID", reflect.TypeOf((*MockRepository)(nil).GetTasksByGroupID), ctx, taskGroupID)
}

// GetTasksByProjectID mocks base method.
func (m *MockRepository) GetTasksByProjectID(ctx context.Context, projectID primitive.ObjectID) ([]*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByProjectID indicates an expected call of GetTasksByProjectID.
func (mr *MockRepositoryMockRecorder) GetTasksByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByProjectID", reflect.TypeOf((*MockRepository)(nil).GetTasksByProjectID), ctx, projectID)
}

// GetTasksByStatus mocks base method.
func (m *MockRepository) GetTasksByStatus(ctx context.Context, statuses []models.TaskStatus) ([]*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByStatus", ctx, statuses)
	ret0, _ := ret[0].([]*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByStatus indicates an expected call of GetTasksByStatus.
func (mr *MockRepositoryMockRecorder) GetTasksByStatus(ctx, statuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByStatus", reflect.TypeOf((*MockRepository)(nil).GetTasksByStatus), ctx, statuses)
}

// GetUserProjects mocks base method.
func (m *MockRepository) GetUserProjects(ctx context.Context, email string) ([]*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProjects", ctx, email)
	ret0, _ := ret[0].([]*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProjects indicates an expected call of GetUserProjects.
func (mr *MockRepositoryMockRecorder) GetUserProjects(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProjects", reflect.TypeOf((*MockRepository)(nil).GetUserProjects), ctx, email)
}

// IncrementFailureStat mocks base method.
func (m *MockRepository) IncrementFailureStat(ctx context.Context, projectID primitive.ObjectID, date string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementFailureStat", ctx, projectID, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementFailureStat indicates an expected call of IncrementFailureStat.
func (mr *MockRepositoryMockRecorder) IncrementFailureStat(ctx, projectID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementFailureStat", reflect.TypeOf((*MockRepository)(nil).IncrementFailureStat), ctx, projectID, date)
}

// StoreTaskFailureStats mocks base method.
func (m *MockRepository) StoreTaskFailureStats(ctx context.Context, stats *models.StoredTaskFailureStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTaskFailureStats", ctx, stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreTaskFailureStats indicates an expected call of StoreTaskFailureStats.
func (mr *MockRepositoryMockRecorder) StoreTaskFailureStats(ctx, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTaskFailureStats", reflect.TypeOf((*MockRepository)(nil).StoreTaskFailureStats), ctx, stats)
}

// UpdateExecutionStatus mocks base method.
func (m *MockRepository) UpdateExecutionStatus(ctx context.Context, executionUUID string, status models.ExecutionStatus, errorMessage *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExecutionStatus", ctx, executionUUID, status, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExecutionStatus indicates an expected call of UpdateExecutionStatus.
func (mr *MockRepositoryMockRecorder) UpdateExecutionStatus(ctx, executionUUID, status, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExecutionStatus", reflect.TypeOf((*MockRepository)(nil).UpdateExecutionStatus), ctx, executionUUID, status, errorMessage)
}

// UpdateProject mocks base method.
func (m *MockRepository) UpdateProject(ctx context.Context, projectID primitive.ObjectID, project *models.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", ctx, projectID, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockRepositoryMockRecorder) UpdateProject(ctx, projectID, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockRepository)(nil).UpdateProject), ctx, projectID, project)
}

// UpdateTask mocks base method.
func (m *MockRepository) UpdateTask(ctx context.Context, taskUUID string, task *models.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, taskUUID, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockRepositoryMockRecorder) UpdateTask(ctx, taskUUID, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockRepository)(nil).UpdateTask), ctx, taskUUID, task)
}

// UpdateTaskGroup mocks base method.
func (m *MockRepository) UpdateTaskGroup(ctx context.Context, taskGroupUUID string, taskGroup *models.TaskGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskGroup", ctx, taskGroupUUID, taskGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskGroup indicates an expected call of UpdateTaskGroup.
func (mr *MockRepositoryMockRecorder) UpdateTaskGroup(ctx, taskGroupUUID, taskGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskGroup", reflect.TypeOf((*MockRepository)(nil).UpdateTaskGroup), ctx, taskGroupUUID, taskGroup)
}

// UpdateTaskGroupState mocks base method.
func (m *MockRepository) UpdateTaskGroupState(ctx context.Context, taskGroupUUID string, state models.TaskGroupState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskGroupState", ctx, taskGroupUUID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskGroupState indicates an expected call of UpdateTaskGroupState.
func (mr *MockRepositoryMockRecorder) UpdateTaskGroupState(ctx, taskGroupUUID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskGroupState", reflect.TypeOf((*MockRepository)(nil).UpdateTaskGroupState), ctx, taskGroupUUID, state)
}

// UpdateTaskGroupStatus mocks base method.
func (m *MockRepository) UpdateTaskGroupStatus(ctx context.Context, taskGroupUUID string, status models.TaskGroupStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskGroupStatus", ctx, taskGroupUUID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskGroupStatus indicates an expected call of UpdateTaskGroupStatus.
func (mr *MockRepositoryMockRecorder) UpdateTaskGroupStatus(ctx, taskGroupUUID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskGroupStatus", reflect.TypeOf((*MockRepository)(nil).UpdateTaskGroupStatus), ctx, taskGroupUUID, status)
}

// UpdateTaskState mocks base method.
func (m *MockRepository) UpdateTaskState(ctx context.Context, taskUUID string, state models.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskState", ctx, taskUUID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskState indicates an expected call of UpdateTaskState.
func (mr *MockRepositoryMockRecorder) UpdateTaskState(ctx, taskUUID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskState", reflect.TypeOf((*MockRepository)(nil).UpdateTaskState), ctx, taskUUID, state)
}

// UpdateTaskStatus mocks base method.
func (m *MockRepository) UpdateTaskStatus(ctx context.Context, taskUUID string, status models.TaskStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, taskUUID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockRepositoryMockRecorder) UpdateTaskStatus(ctx, taskUUID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockRepository)(nil).UpdateTaskStatus), ctx, taskUUID, status)
}
